server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size:  20MB #최대 20MB
      max-request-size:  20MB
  datasource:
    url: jdbc:mysql://localhost:3306/bringiton?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234
#    sql:
#      init:
#        schema-locations:
#        - classpath:db/table.sql
#        data-locations:
#        - classpath:db/data.sql

#h2:
#  console:
#    enabled: true
#  output:
#    ansi:
#    enabled: always

mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.mybatis: DEBUG

#초기 파라미터 설정
  # tenco:
  # key:  915672AEF5ACD1F1EED0CC56FD1256ABE488B6DA2A21A42E2BAFF25DF5D25198
